apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-anotasi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server-anotasi 
  template:
    metadata:
      labels:
        app: web-server-anotasi
      annotations: 
        deskripsi: ini merupakan aplikasi yang dibuat nginx. nginx adalah suatu web server yang di gunakan oleh banyak orang di seluruh dunia.
    spec:
      containers:
      - name: web-server-anotasi
        image: nginx
        ports:
        - containerPort: 3000
