apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server-labels
  template:
    metadata:
      labels:
        app: web-server-labels
    spec:
      containers:
      - name: web-server
        image: nginx:alpine
        ports:
        - containerPort: 8000
