apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:9.6-alpine
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: config-env
